server:
  port: ${SERVER_PORT:8000}

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:

      # User service
        - id: user-service
          uri: http://user-service:8100
          predicates:
          - Path=/api/auth/**

      # Product service
        - id: product-service
          uri: http://product-service:8200
          predicates:
          - Path=/api/products/**

      # AI service
        - id: ai-content-service
          uri: http://ai-content-service:8300
          predicates:
          - Path=/api/ai/**

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true