services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_DATABASE: user_service_db
      MYSQL_ROOT_PASSWORD: 1AOarw==
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  user-service:
    build: .
    container_name: user-service
    ports:
      - "8100:8100"
    env_file:
      - .env
    depends_on:
      - mysql

volumes:
  mysql_data: